### PR TITLE
Add data folder, parks geojson

### PR DESCRIPTION
**Pull request by lyzidiamond**

### CODE REVIEW

**Comment by lyzidiamond** [comment]
Don't merge this yet -- gonna add a fields reference file.

**Comment by junosuarez** [comment]
:+1:

**Comment by lyzidiamond** [comment]
Okay NOW it's good to go :smiley:

**Comment by eeeschwartz** [comment]
how would you feel about moving the files to public/data? That will allow the webserver to hand it out to the world

**Comment by lyzidiamond** [comment]
I will do that. Commit forthcoming.

**Comment by lyzidiamond** [comment]
Donezo.

**Pull request merged**
